name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci_msvc:
    runs-on: windows-latest
    name: CI MSVC
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check CMake version
        run: cmake --version

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Generate CMake project
        run: cmake -S. -Bbuild

      - name: Build 64bit release DLL
        run: cmake --build build --config RelWithDebInfo

      - name: Rename ASI to CLS-${{ github.sha }}.asi
        run: ren CLS.asi CLS-${{ github.sha }}.asi
        working-directory: build/RelWithDebInfo

      - name: Upload Artifact (asi)
        uses: actions/upload-artifact@v4
        with:
          name: binary-MSVC
          path: build/RelWithDebInfo/CLS-*.asi

      - name: Upload Artifact (pdb)
        uses: actions/upload-artifact@v4
        with:
          name: pdb-MSVC
          path: build/RelWithDebInfo/CLS.pdb